### ISSUE TITLE
better design 

### ISSUE THREAD

**Issue by prinzpiuz** [prinzpiuz/OpenTasky#4]
currently we dont have any design for our app 
if we can have minimal design (at least correct alignment for page it will be awesome)

**Comment by azhsetiawan** [comment]
hi @prinzpiuz
i wanna help implement better design for this repo. would you update how to run in readme?
i'm on macOS 10.14.3 and using node v10.16.3 and npm 6.11.3

**Comment by prinzpiuz** [comment]
we use postgress as our db ..so you need to create db in the name "task" with username "task" and password "task"
or if you want to make them as you like can make a db and password as you like and change current one in util/db.js

**Comment by azhsetiawan** [comment]
after `npm start` i got this error

`Executing (default): INSERT INTO "users" ("id","name","email","password","status","role","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING *;
Failed to prune sessions: relation "session" does not exist`

did i miss something?

**Comment by prinzpiuz** [comment]
Sorry you need to create a table session inside task db...to store sessions

**Comment by prinzpiuz** [comment]
let me look it ... and thank you very much for your effort

**Comment by prinzpiuz** [comment]
is there any way i can contact you ? personally

**Comment by azhsetiawan** [comment]
my username in telegram/twitter/dribbble/instagram is same as github username
