### ISSUE TITLE
need a method to create session table inside db 

### ISSUE THREAD

**Issue by prinzpiuz** [prinzpiuz/OpenTasky#7]
need a method to create session table inside db .. now we manually creating  the session table

**Comment by azhsetiawan** [comment]
@prinzpiuz i've solved this problem before from this documentation https://www.npmjs.com/package/connect-pg-simple

maybe we just update readme, add how-to run local development by run this
`psql mydatabase < node_modules/connect-pg-simple/table.sql`

**Comment by prinzpiuz** [comment]
@azhsetiawan will update the readme
